export const communityUrls = [
    { name: "금강FM", channel: "keumkangfm", streamUrl: "http://icecast.radios.kr:8000/keumkangfm" },
    { name: "영주FM", channel: "yeongjufm", streamUrl: "http://icecast.radios.kr:8000/yeongjufm" },
    { name: "관악FM", channel: "gwanakfm", streamUrl: "http://icecast.radios.kr:8000/gwanakfm" },
    { name: "광주FM", channel: "kjfm", streamUrl: "http://radiostream.communityradio.kr/live" },
    { name: "마포FM", channel: "mapofm", streamUrl: "http://onair.mapofm.net/mapofm" },
    { name: "성남FM", channel: "seongnamfm", streamUrl: "http://onair.mapofm.net/seongnamfm" },
    { name: "성서공동체FM", channel: "scnfm", streamUrl: "http://onair.mapofm.net/scnfm" },
    { name: "옥천FM", channel: "obn", streamUrl: "http://icecast.radios.kr:8000/obn" },
    { name: "세종FM", channel: "sejongfm", streamUrl: "http://icecast.radios.kr:8000/sejongfm" },
    { name: "GBS고려방송", channel: "crfm", streamUrl: "http://icecast.radios.kr:8000/crfm" },
    { name: "한밭FM", channel: "hanbatfm", streamUrl: "http://icecast.radios.kr:8000/hanbatfm" },
    { name: "성주FM", channel: "sjfm", streamUrl: "http://icecast.radios.kr:8000/sjfm" },
    { name: "남해FM", channel: "namhaefm", streamUrl: "http://icecast.radios.kr:8000/namhaefm" },
    { name: "상주FM", channel: "sangjufm", streamUrl: "http://icecast.radios.kr:8000/sangjufm" },
    { name: "서대문FM", channel: "sdmfm", streamUrl: "http://icecast.radios.kr:8000/sdmfm" },
    { name: "수원FM", channel: "sonefm", streamUrl: "http://onair.mapofm.net/sonefm" },
    { name: "우리FM", channel: "yeonjefm", streamUrl: "http://icecast.radios.kr:8000/yeonjefm" },
    { name: "순천미디어네트워크", channel: "suncheonfm", streamUrl: "http://icecast.radios.kr:8000/suncheonfm" },
    { name: "구리FM", channel: "gurifm", streamUrl: "http://icecast.radios.kr:8000/gurifm" },
    { name: "대구동구FM", channel: "daegufm", streamUrl: "http://icecast.radios.kr:8000/daegufm" },
    { name: "전주FM", channel: "jcfm", streamUrl: "http://radiostream.communityradio.kr/jcfm1" },
    { name: "단원FM", channel: "dwfm", streamUrl: "http://radiostream.communityradio.kr/dwfm1" },
    { name: "태백FM", channel: "taebaekfm", streamUrl: "http://icecast.radios.kr:8000/taebaekfm" },
];